version: "3"
services:
  webserver:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        VARIANT: 7.3
        NODE_VERSION: "lts/*"
    restart: always
    network_mode: service:db
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
volumes:
  mariadb-data: